language: go

go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"

services:
  - docker

before_install:
  - make install

script:
#  - make lint
  - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.30.0 golangci-lint run -v
  - make ci-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
