language: go

go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"

before_install:
  - make install

script:
  - make lint
  - make ci-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
